# Permalinks
permalink:        pretty

# Setup
title:            Trevor Ware
tagline:
url:              http://twarrre.github.io
paginate:         1
baseurl:          /
author:
  name:           Trevor Ware
  url:            https://twitter.com/twarrre
  email:          trevorware@outlook.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/twarrre/twarrre.github.io

pages_list:
  About: '/'
  Games: '/games'
  #Software: '/software'
  #Art: '/art'
  #Blog: '/blog'
  #Contact: '/contact'

twitter_username: twarrre
github_username:  twarrre
facebook_username: twarrre
instagram_username: twarrre
linkedin_username: twarrre
